services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    # environment:
    #   COMPOSER_ALLOW_SUPERUSER: 1

  mysql_db:
    image: mysql:8.0
    container_name: mysql_app_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_app_db_data:/var/lib/mysql

volumes:
  mysql_app_db_data:
